STORAGE_BACKEND: "local"
LS_INPUT_PATH: "validation_data/orders-500.log"
LS_OUTPUT_PATH: "validation_data/aug-3_25-results.txt"
INFER_ANOMALY_THRESHOLD: 1.3
INFER_TIME_SPAN: 1
INFER_LOOPS: 1
PARALLELISM: 6
MODEL_DIR: ./logs/models/
