language: python
python:
  - "3.6.7"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - LOCAL_DATA_FILE=../validation_data/Hadoop_2k.json
    - LOCAL_RESULTS_FILE=/tmp/local-results.txt
install:
  - "pip install pipenv"
  - "pipenv install --deploy"
script:
  - "pipenv run pytest"
