STORAGE_DATASOURCE: "local.source"
STORAGE_DATASINK: "local.sink"
LS_INPUT_PATH: "validation_data/Hadoop_2k.json"
LS_OUTPUT_PATH: "/tmp/local-results.txt"
W2V_MIN_COUNT: 1
W2V_ITER: 500
W2V_COMPUTE_LOSS: "True"
W2V_SEED: 50
W2V_WORKERS: 1
